// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvFkHadv0ayGoexl2yT0R6cYz9DCUISgg',
    appId: '1:604076523173:web:2d281b1f258ec7b7ff974c',
    messagingSenderId: '604076523173',
    projectId: 'movers-81e3a',
    authDomain: 'movers-81e3a.firebaseapp.com',
    storageBucket: 'movers-81e3a.firebasestorage.app',
    measurementId: 'G-Y49HJKT7ZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8a-06xcWD-CqDNACDdTGq6JwImcvsbac',
    appId: '1:604076523173:android:7fb15acb291a2a4dff974c',
    messagingSenderId: '604076523173',
    projectId: 'movers-81e3a',
    storageBucket: 'movers-81e3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh61Yj-9TEA3uIDghlg7asgXB5k7FqoXk',
    appId: '1:604076523173:ios:8d3f4eae38b00523ff974c',
    messagingSenderId: '604076523173',
    projectId: 'movers-81e3a',
    storageBucket: 'movers-81e3a.firebasestorage.app',
    androidClientId: '604076523173-1eep5la5mv0cvi0ie8kavmeoflr07bvq.apps.googleusercontent.com',
    iosBundleId: 'com.example.movers',
  );
}
